sonar.host.url=https://sonarcloud.io

sonar.projectKey=oscar-alvarado24-empleado-backend-sm

sonar.organization=oscar-alvarado24

# Rutas del código fuente
sonar.sources=src

# Rutas de tests (opcional)
sonar.tests=tests

# Inclusión de archivos de test
sonar.test.inclusions=**/*.test.js,**/*.spec.js

# Reporte de cobertura
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Exclusiones
sonar.coverage.exclusions=**/*.test.js,**/*.spec.js,**/node_modules/**
sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**,**/*.config.js