// src/application/use_cases/CreateEmployee.js
const Employee = require('../../domain/entities/Employee');

class CreateEmployee {
  constructor(employeeRepository) {
    this.employeeRepository = employeeRepository;
  }

  async execute(employeeData) {
    // Any validation or business logic before creation can go here
    // For example, ensuring email is unique might be a domain concern or handled by DB constraints,
    // but some initial checks can happen here.
    const { firstName, lastName, email, position, department } = employeeData;
    // ID is typically generated by the database, so we don't pass it here.
    const employee = new Employee(null, firstName, lastName, email, position, department);
    return this.employeeRepository.save(employee);
  }
}

module.exports = CreateEmployee;
