// src/domain/entities/Employee.js
class Employee {
  constructor(id, firstName, lastName, email, position, department) {
    this.id = id; // Can be generated by the database or a UUID
    this.firstName = firstName;
    this.lastName = lastName;
    this.email = email;
    this.position = position;
    this.department = department; // Added department as an example
  }
}

module.exports = Employee;
